services:
  - mongodb
language: node_js
node_js:
  - "4.2.2"
  - "5.0.0"


sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
